version: ~> 1.0
sudo: false
language: node_js
node_js:
  - '10'
  - '12'
  - '14'
  - '15'
matrix:
  fast_finish: true
  allow_failures: []
cache: npm
install:
  - >-
    eval "$(curl -fsSL
    https://raw.githubusercontent.com/bevry/awesome-travis/master/scripts/node-install.bash)"
before_script:
  - >-
    eval "$(curl -fsSL
    https://raw.githubusercontent.com/bevry/awesome-travis/master/scripts/node-verify.bash)"
after_success:
  - >-
    eval "$(curl -fsSL
    https://raw.githubusercontent.com/bevry/awesome-travis/master/scripts/node-publish.bash)"
notifications:
  email:
    recipients: >-
      HfMM9dvBhMOVieJwCMPUtebG2RqmQEPkOK8OqGTyJlcpp85vwK10us1AITsRDU7Ku69inWujGj/l6wFaYQIMVK3A43yBHr/6OtuCnkN0UiL1MXkOqyLMnVlAcXh6XtgSkc6jm8+JDATU/21xc/4JWvJAF7b3sFBsQOb53mdndp6upc+EcF9mPcvQnQQ8FTOfhMUMIxe5SlquwUjEJewpzoRRpy+0wg972qU+DiNHB4xKtUI0zKePG6TLvZIY+GLIHkrYlMKO1fwI2RWq9vbCFIhNnf/roq/0+XeYWwtUD/DjIOmNC0PNdF+JqqoRUwTattZpTo0WrXDCRRXTU/0nl9j4jNSyZ8/uT8R6cREAZLo5L70XydxNSP+ZB7Kd0EStickezGp+0nLekInGUdXzy2TzAVJP59Ng4yprTJs+2xBLMzAF7uuNvuHYZMb6DGVSjpJtNBorCUvjsJYEolxv7i+HaISlth79G+ao5vmAgLO/6x880Wicp6JnI6gnPyxynMYZd5a4Jss6Id4SsG16UEiDoPdHJnrA+HNgfzW4VLWesF+dW1T5UII/2Hok0HPBSdX6HRlhZcKgxLzSowTWxZps6CR95t0d1eTp/Eqo6jH16M8ce1PqqyG7/VznEtkW3P2q+0CJJ67/ydmP5Vfuq0Hyx7WUYwHEj052J6+grZU=
